"""describe change

Revision ID: 0751fe441c9d
Revises: 3933da90f599
Create Date: 2025-10-24 23:30:28.252094

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0751fe441c9d"
down_revision: str | None = "3933da90f599"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
