repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["--toml", "pyproject.toml"]

  - repo: local
    hooks:
      - id: biome-check
        name: biome check (frontend)
        entry: npx @biomejs/biome check
        language: system
        types_or: [javascript, typescript, tsx, jsx, json]
        files: ^src/frontend/
        pass_filenames: false
